services:
  recognition_api:
    extends:
      service: recognition_api
      file: ./backend/recognition_api/recognition-api-compose.yml
    working_dir: ./backend/recognition_api
    networks:
      - recognition_net

  recognition_model:
    extends:
      service: recognition_model
      file: ./backend/recognition_model/recognition-model-compose.yml
    working_dir: ./backend/recognition_model
    networks:
      - recognition_net

networks:
  recognition_net:
    driver: bridge
