services:
  recognition_api:
    extends:
      service: recognition_api
      file: ./backend/recognition_api/docker-compose.yml
    networks:
      - recognition_net

  recognition_model:
    extends:
      service: recognition_model
      file: ./backend/recognition_model/docker-compose.yml
    networks:
      - recognition_net

  recognition_frontend:
    extends:
      service: recognition_frontend
      file: ./frontend/docker-compose.yml

networks:
  recognition_net:
    driver: bridge
