services:
  recognition_api:
    container_name: recognition_api
    build:
      context: .
      dockerfile: ./backend/recognition_api/Dockerfile
    env_file: ./backend/recognition_api/.env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - recognition_net

  recognition_model:
    container_name: recognition_model
    build:
      context: .
      dockerfile: ./backend/recognition_model/Dockerfile
    expose:
      - 50051
    networks:
      - recognition_net

  recognition_frontend:
    container_name: recognition_frontend
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    expose:
      - 80
    ports:
      - "4200:80"

networks:
  recognition_net:
    driver: bridge
