version: '3.12'

services:
  recognition_api:
    build: .
    container_name: recognition_api_container
    env_file: .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
