services:
  recognition_api:
    build: .
    container_name: recognition_api
    env_file: .env
    environment:
      - RECOGNITION_API_CONTAINER_PORT=${RECOGNITION_API_CONTAINER_PORT}
      - RECOGNITION_API_HOST_PORT=${RECOGNITION_API_HOST_PORT}
    ports:
      - "127.0.0.1:${RECOGNITION_API_HOST_PORT}:${RECOGNITION_API_CONTAINER_PORT}"
