services:
  recognition_api:
    build: .
    container_name: recognition_api
    env_file: .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - HOST_PORT=${HOST_PORT}
    ports:
      - "127.0.0.1:${HOST_PORT}:${BACKEND_PORT}"
