# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class NeuralServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessText = channel.unary_unary(
        '/backend.NeuralService/ProcessText',
        request_serializer=service__pb2.TextRequest.SerializeToString,
        response_deserializer=service__pb2.TextResponse.FromString,
        )


class NeuralServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProcessText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NeuralServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessText': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessText,
          request_deserializer=service__pb2.TextRequest.FromString,
          response_serializer=service__pb2.TextResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'backend.NeuralService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
