name: Test and Deploy

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test-gesture-recognition-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/recognition_api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Set up .env file
        run: |
          touch .env
          echo '${{ secrets.ENV_FILE }}' > .env

      - name: Run tests
        run: poetry run pytest tests

  deploy:
    needs: test-gesture-recognition-api
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up .env file
        run: |
          touch ./backend/recognition_api/.env
          echo '${{ secrets.ENV_FILE }}' > ./backend/recognition_api/.env

      - name: Copy project to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            mkdir -p ~/gesture_recognition/backend/recognition_api
          EOF
  
          rsync -az --delete ./backend/recognition_api/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/gesture_recognition/backend/recognition_api

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/gesture_recognition/backend/recognition_api
            docker compose down
            docker compose up -d --build
          EOF
